### ISSUE TITLE
tippy-1.1.0 Crash

### ISSUE THREAD

**Issue by Trnrr** [vini2003/Clippys-Tippies#1]
Got crash when I tried to create a world - https://gist.githubusercontent.com/Cloak-Bot/19295fc24937791b3cb70231a694c888/raw/e77c7419e9356ae191e9b8d833e065750cb07884/crash.txt

**Comment by vini2003** [comment]
i did a very big dumb and marked a 1.14 build as 1.15, then forgot to upload the 1.15 one

big brain time

**Comment by vini2003** [comment]
should maybe perhaps be solved
